spring.application.name=api-clientes

server.port=8081

datasource.host=jdbc:postgresql://localhost:5432/bd-api-clientes
datasource.user=postgres
datasource.pass=coti

# permissões de CORS
cors.enabled=hhtp://localhost:4200